server:
  port: 10110
spring:
  application:
    name: auth-service
  flyway:
    clean-disabled: true
    clean-on-validation-error: false
    out-of-order: true
    enabled: true
    locations: classpath:db/migration/sql
    password: admin
    url: jdbc:postgresql://localhost:5434/
    user: admin
    ignore-migration-patterns:

  