server:
  port: 10110
spring:
  application:
    name: auth-service
  flyway:
    clean-disabled: true
    clean-on-validation-error: false
    out-of-order: true
    enabled: true
    locations: classpath:db/migration/sql
    url: jdbc:postgresql://localhost:5434/auth_db
    user: postgres
    password: postgres123
  datasource:
    url: jdbc:postgresql://localhost:5434/auth_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/auth_db
    username: postgres
    password: postgres123
logging:
  level:
    com.labs.pfit.auth_service: DEBUG
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.postgresql: DEBUG
    io.r2dbc.spi: DEBUG
    io.r2dbc.pool: DEBUG
    org.flywaydb.core: INFO
    org.springframework.boot: INFO
    org.springframework.boot.autoconfigure.flyway: INFO
    org.springframework.boot.autoconfigure.jdbc: INFO
