server:
  port: 10120
spring:
  application:
    name: finance-service
  flyway:
    clean-disabled: true
    clean-on-validation-error: false
    out-of-order: true
    enabled: true
    locations: classpath:db/migration/sql
  datasource:
    url: jdbc:postgresql://localhost:5434/finance_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
logging:
  level:
    com.labs.pfit.finance_service: DEBUG
    org.springframework: INFO
