server:
  port: 10120
spring:
  application:
    name: finance-service
  flyway:
    clean-disabled: true
    clean-on-validation-error: false
    out-of-order: true
    enabled: true
    locations: classpath:db/migration/sql
    url: jdbc:postgresql://localhost:5434/finance_db
    user: postgres
    password: postgres123
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/finance_db
    username: postgres
    password: postgres123

logging:
  level:
    com.labs.pfit.finance_service: DEBUG
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.postgresql: DEBUG
    io.r2dbc.spi: DEBUG
    io.r2dbc.pool: DEBUG
    org.flywaydb.core: INFO
    org.springframework.boot: INFO
    org.springframework.boot.autoconfigure.flyway: INFO
    org.springframework.boot.autoconfigure.jdbc: INFO
