server:
  port: 10120
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/finance_db
    username: admin
    password: admin
  application:
    name: finance-service
  flyway:
    enabled: true
    locations: classpath:db/migration/sql
